#!/bin/bash
#-------------------------------------------------------------------------------

if [[ -f `pwd`/functions ]]; then
  source functions
else
  echo "Archivo no disponible: functions"
  exit 1
fi
bienvenidos(){
  clear
  echo -e "${Bold}BIENVENIDOS AL MENU DE INSTALACION DRIVERS/ESCRITORIO/APLICACIONES${White}"
  print_line
  echo "Requerimientos:"
  echo "-> Instalacion Sistema Base ArchLinux"
  echo "-> Ejecutar Instalador como usuario root"
  echo "-> Conexión a Internet"
  print_line
  echo "Para Cancelar la Instalacion Precione CTRL+C"
  echo "http://www.github.com/archlinuxlatino/ISA"
  echo "visita nuestras redes @archlinuxlatino"
  print_line
  echo -e "\nCopias de Seguridad:"
  print_line
  # backup old configs
  [[ ! -f /etc/pacman.conf.backup ]] && cp -v /etc/pacman.conf /etc/pacman.conf.backup || echo "/etc/pacman.conf.backup";
  [[ -f /etc/ssh/sshd_config.backup ]] && echo "/etc/ssh/sshd_conf.backup";
  [[ -f /etc/sudoers.backup ]] && echo "/etc/sudoers.backup";
  pause_function
  echo ""
}
#finalizar{{{
finish(){
  print_title "INSTALACIONN COMPLETA - DISFRUTA DE TU NUEVO SISTEMA OPERATIVO..."
  echo -e "Gracias por usar el script de instalacion de  Archlinux\n"
  #REBOOT
  read -p "Reiniciar su Sistema [s/N]: " OPTION
  [[ $OPTION == s ]] && reboot
  exit 0
}
salir(){
  exit 0
}
#}}}
#Limpiar Cache{{{
limpiar_cache(){
  print_title "CLEAN ORPHAN PACKAGES"
  pacman -Rsc --noconfirm $(pacman -Qqdt)
  #pacman -Sc --noconfirm
  pacman-optimize
}
#}}}
#RECONFIGURE SYSTEM {{{
reconfigurar_sistema(){
  print_title "NOMBRE MAQUINA - HOSTNAME"
  read -p "Nombre [ex: archlinux]: " HN
  hostnamectl set-hostname $HN

  print_title "ZONA HORARIA - TIMEZONE"
  OPTION=n
  while [[ $OPTION != s ]]; do
    settimezone
    read_input_text "Confirmar timezone ($ZONE/$SUBZONE)"
  done
  timedatectl set-timezone ${ZONE}/${SUBZONE}

  print_title "RELOJ PC "
  hwclock_list=('UTC' 'Localtime');
  PS3="$prompt1"
  select OPT in "${hwclock_list[@]}"; do
    case "$REPLY" in
      1)
        timedatectl set-local-rtc false
        ;;
      2)
        timedatectl set-local-rtc true
        ;;
      *) invalid_option ;;
    esac
    [[ -n $OPT ]] && break
  done
  timedatectl set-ntp true
}
#}}}
check_root
check_iso
check_archlinux
check_hostname
check_connection
check_pacman_blocked
check_multilib
pacman_key
system_update
bienvenidos
while true
do
  print_title "INSTALADOR DE ARCHLINUX 2020-05 DESPUES DEL SISTEMA BASE"
  echo ""
  echo "  1) $(mainmenu_item "${checklist[1]}" "Agregar Usuario Sudo")"
  echo "  2) $(mainmenu_item "${checklist[2]}" "Configuracion Basica")"
  echo "  3) $(mainmenu_item "${checklist[3]}" "Instalar Gestor AUR")"
  echo "  4) $(mainmenu_item "${checklist[4]}" "Configurar Driver/Video/XORG")"
  echo "  5) $(mainmenu_item "${checklist[5]}" "Instalar Driver Adicionales")"
  echo "  6) $(mainmenu_item "${checklist[6]}" "Configurar Escritorio Ventana")"
  echo "  7) $(mainmenu_item "${checklist[7]}" "Configurar Escritorio Mosaico (PROXIMAMENTE)")"
  echo "  8) $(mainmenu_item "${checklist[8]}" "Configurar Red")"
  echo "  9) $(mainmenu_item "${checklist[9]}" "Intalar Aplicaciones")"
  echo " 10) $(mainmenu_item "${checklist[10]}" "Reconfigurar Sistema")"
  echo " 11) $(mainmenu_item "${checklist[11]}" "Limpiar Cache/Huerfanos")"
  echo ""
  echo " m) Regresar al Menu Principal"
  echo ""
  echo " s) Salida"
  echo ""
  MAINMENU+=" s"
  read_input_options "$MAINMENU"
  for OPT in ${OPTIONS[@]}; do
    case "$OPT" in
      1)
        sources/./01-user
        checklist[1]=1
        ;;
      2)
        sources/./02-basicos
        checklist[2]=1
        ;;
      3)
        sources/./03-aur
        checklist[3]=1
        ;;
      4)
        sources/./04-video-card
        checklist[4]=1
        ;;
      5)
        sources/./05-driver-adicionales
        checklist[5]=1
        ;;
      6)
        sources/./06-desk-ven
        checklist[6]=1
        ;;
      7)
        #sources/./07-desk-mosa
        checklist[7]=1
        ;;
      8)
        sources/./08-network
        checklist[8]=1
        ;;
      9)
        sources/./09-aplicaciones
        checklist[8]=1
        ;;
      10)
        reconfigurar_sistema
        checklist[8]=1
        ;;
      11)
        limpiar_cache
        ;;
      "m")
        ./setuparch
        salir
        ;;
      "s")
        finish
        ;;
      *)
        invalid_option
        ;;
    esac
  done
done
